version: "3"

services:
  httpd:
    build: ./apache-php-mysqli
    container_name: httpd
    ports:
      - "8080:80"
    volumes:
      - ./httpd/htdocs:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 3278
    volumes:
      - ./mariadb/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: mariadb
    ports:
      - "8096:80"
